#!/usr/bin/env bash
# a script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5456-web
    bind *:80
    mode http
    balance roundrobin
    server 162549-web-01 100.25.220.212:80 check
    server 5456-web-02 18.234.231.105:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
