#!/usr/bin/env bash
# this script installs the 'ufw' firewall and sets rules

apt-get install ufw
sed -i 's/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
